# Generated by Django 5.1.6 on 2025-02-09 22:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("password", models.CharField(db_index=True, max_length=500)),
                ("role", models.CharField(max_length=20)),
                ("bio", models.TextField()),
                ("avatar", models.CharField(max_length=1000)),
                ("wallpaper", models.CharField(max_length=1000)),
                (
                    "create_datetime",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_email", models.EmailField(db_index=True, max_length=254)),
                ("access_token", models.CharField(db_index=True, max_length=100)),
                (
                    "create_datetime",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountPasscode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_email", models.EmailField(db_index=True, max_length=254)),
                ("passcode", models.CharField(db_index=True, max_length=10)),
                (
                    "create_datetime",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Follower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("follower_email", models.EmailField(db_index=True, max_length=254)),
                ("followed_email", models.EmailField(db_index=True, max_length=254)),
                ("read", models.BooleanField(default=False)),
                (
                    "create_datetime",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
        ),
    ]
