# Generated by Django 5.1.6 on 2025-02-09 22:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=200)),
                ("content", models.TextField()),
                ("images", models.CharField(max_length=2000)),
                ("poster_email", models.EmailField(db_index=True, max_length=254)),
                ("likes", models.IntegerField(default=0)),
                ("views", models.IntegerField(default=0)),
                ("channel", models.CharField(db_index=True, max_length=100)),
                (
                    "create_datetime",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LikedPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "liked_account_email",
                    models.EmailField(db_index=True, max_length=254),
                ),
                ("poster_email", models.EmailField(db_index=True, max_length=254)),
                ("read", models.BooleanField(default=False)),
                (
                    "create_datetime",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="post.post"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent_comment_id", models.BigIntegerField(db_index=True)),
                ("poster_email", models.EmailField(db_index=True, max_length=254)),
                ("commentator_email", models.EmailField(db_index=True, max_length=254)),
                ("comment", models.TextField()),
                ("read", models.BooleanField(default=False)),
                (
                    "create_datetime",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="post.post"
                    ),
                ),
            ],
        ),
    ]
